### ISSUE TITLE
Add to the fake player to receive Whisper from a normal player

### ISSUE THREAD

**Issue by EricksOliveira** [Viste/OutlandCore#1]
##### SMALL DESCRIPTION:

When sending the message to the fake player, upon receiving the string. the normal player will soon know that it is a fake message!

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal player should send Whisper to the fake player normally. That way it wouldn't look like a fake player!

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create new character
2. send a whisper to the fake player
3. See that the received string is a "fake" message

##### BRANCH(ES):

master

**Comment by Viste** [comment]
https://github.com/WarheadCore/WarheadCore
