### ISSUE TITLE
Crossfaction BG Error in Arenas Team

### ISSUE THREAD

**Issue by diegobfl** [Viste/Outlandcore#1]
Description: Crossfaction BG Error in Arenas Team.

Current Behavior: I tested Crossfaction on BG and everything went well, but when I went to create 2x2 Arenas Teams to test an incoming error happened between two teams of the HORDE faction, they enter the arena on the same side, causing a very serious error for the functionality of the repository.

![image](https://user-images.githubusercontent.com/26128664/39678657-db7c97c8-5166-11e8-97d3-5895292cc5d2.png)
![image](https://user-images.githubusercontent.com/26128664/39678659-e32ae04c-5166-11e8-94e6-42434a6b04d4.png)

![image](https://user-images.githubusercontent.com/26128664/39678662-e9a98c02-5166-11e8-96b8-205720cb9c05.png)

Steps to reproduce the problem:

Correct the correct coordinates when teams enter the arena and stand on opposite sides to take the battle with the two teams on each side.

Branch (s): master
AChash / commit: last
Operating system: Windows 2008 r2
Modules: no

**Comment by diegobfl** [comment]
any news?

**Comment by Viste** [comment]
can't reproduce bug >_<

**Comment by vhipercode** [comment]
@Viste  you have no idea how to fix this?

**Comment by Viste** [comment]
@vhipercode i CAN'T REPRODUCE bug so i CAN'T FIX IT WHEN NO BUG FOR ME

**Comment by Viste** [comment]
to do a fix need to reproduce bug and detect where, i stuck into first on trying to reproduce

**Comment by BarbzYHOOL** [comment]
Yes, retest vhiper and explain how to have that bug

**Comment by diegobfl** [comment]
@BarbzYHOOL @Viste 
create 2x2 Arenas Teams to test an incoming error happened between two teams of the HORDE faction, they enter the arena on the same side, causing a very serious error for the functionality of the repository.

![image](https://user-images.githubusercontent.com/26128664/40240539-2078bb6e-5a8f-11e8-8aa6-f6a88b63d6cb.png)

**Comment by diegobfl** [comment]
@Viste @BarbzYHOOL Tested and confirmed the error in the arenas, see that the teams are only going to the (Green Team) - (Gold Team) is zeroed that is the error

**Comment by Viste** [comment]
i reproduce the bug so now i can fix it and i need coupl days for it(work and home stuff)

**Comment by diegobfl** [comment]
@Viste greetings friend, have you predicted to fix?

**Comment by Viste** [comment]
@diegobfl what you want? don't understend you 
as i say i need some days to do my stuff in real life then i fix it, want fast fix pay $, don't want pay wait pls and don't be annoing
