### ISSUE TITLE
BG template not work properly

### ISSUE THREAD

**Issue by Dreaxxx** [Viste/Outlandcore#2]
Description: BG template not work properly

Current behaviour: In the DB , when we configure for exemple 5 MinPlayersPerTeam for the Random BG in the BGtemplate ,  and we configure 15 MinPlayerPerTeam for other BG like Alterac Valley , when 5 players tag , they can end up at 5 in the alterac valley , so the BgTemplate not work properly with the CFBG script

Expected behaviour: If we have ** players tag in Random BG , they can't end up in BG who need more than ** players to start.

Steps to reproduce the problem:

1. Configure for exemple 5 playerMin for Random BG in the DB
2. Configure for exemple 15 playerMins for IsleOfConquest
3. Tag with 4 other player in game , you could join the IsleofConquest with the random BG (but she will close after 5 mins because you have not the count.

Branch(es): CrossFactionBattleground

AC hash/commit:  7a8b8ea

Operating system:  Linux Débian

Modules:  Transmog / Eluna

Other Customizations: /

**Comment by Viste** [comment]
thx
